version: '3'

services:
  # post-service
  post-service:
    container_name: post-service
    build:
      context: ./
      dockerfile: ./post-service.dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      CODE_EXP_MINUTES: ${CODE_EXP_MINUTES}
      GOOGLEMAIL_DOMAINS: ${GOOGLEMAIL_DOMAINS}
      MYSQL_DSN: ${MYSQL_DSN}
      REDIS_DSN: ${REDIS_DSN}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      ACCESS_SECRET: ${ACCESS_SECRET}
      ACCESS_EXP_MINUTES: ${ACCESS_EXP_MINUTES}
      REFRESH_SECRET: ${REFRESH_SECRET}
      REFRESH_EXP_MINUTES: ${REFRESH_EXP_MINUTES}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      
  # MySQL
  mysql:
    container_name: mysql
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    volumes:
      - './db/mysql/data:/var/lib/mysql'
      - './db/mysql/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './db/mysql/sql:/docker-entrypoint-initdb.d'

  # Redis
  redis:
   container_name: redis
   image: 'redis:6.2-alpine'
   restart: always
   ports:
     - "6379:6379"
   command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
   volumes: 
      - ../db/redis:/data