basePath: /v1
definitions:
  handlers.Response:
    properties:
      data: {}
      error:
        type: boolean
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: Artem Kostenko
    url: https://github.com/aerosystems
  description: Simple REST API for CRUD operations with comments & posts enity.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Nix Trainee 5-6-7-8 tasks
  version: "1.0"
paths:
  /comments:
    get:
      consumes:
      - application/json
      - text/xml
      produces:
      - application/json
      - application/xml
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: get all comments
      tags:
      - comments
swagger: "2.0"
