basePath: /v1
definitions:
  handlers.CodeRequestBoby:
    properties:
      code:
        example: 123456
        type: integer
    type: object
  handlers.RegistrationRequestBody:
    properties:
      email:
        example: example@gmail.com
        type: string
      password:
        example: P@ssw0rd
        type: string
    type: object
  handlers.Response:
    properties:
      data: {}
      error:
        type: boolean
      message:
        type: string
    type: object
  models.Comment:
    properties:
      body:
        example: fuga aut est delectus...
        type: string
      email:
        example: lindsey@caitlyn.net
        type: string
      id:
        example: 302
        type: integer
      name:
        example: quia voluptatem...
        type: string
      postId:
        example: 61
        type: integer
    type: object
  models.Post:
    properties:
      body:
        example: dolore maxime saepe...
        type: string
      id:
        example: 61
        type: integer
      title:
        example: voluptatem doloribus...
        type: string
      userId:
        example: 7
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    name: Artem Kostenko
    url: https://github.com/aerosystems
  description: Simple REST API for CRUD operations with Comments & Posts enities.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: NIX Trainee 5-6-7-8 tasks
  version: "1.0"
paths:
  /comments:
    get:
      consumes:
      - application/json
      - text/xml
      produces:
      - application/json
      - application/xml
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handlers.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Comment'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: get all comments
      tags:
      - comments
  /comments/{id}:
    delete:
      consumes:
      - application/json
      - text/xml
      parameters:
      - description: Comment ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      - application/xml
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: delete comment by ID
      tags:
      - comments
    get:
      consumes:
      - application/json
      - text/xml
      parameters:
      - description: Comment ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      - application/xml
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handlers.Response'
            - properties:
                data:
                  $ref: '#/definitions/models.Comment'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: get comment by ID
      tags:
      - comments
    patch:
      consumes:
      - application/json
      - text/xml
      parameters:
      - description: Comment ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      - application/xml
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handlers.Response'
            - properties:
                data:
                  $ref: '#/definitions/models.Comment'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: particular update comment by ID
      tags:
      - comments
    post:
      consumes:
      - application/json
      - text/xml
      parameters:
      - description: Comment ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      - application/xml
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handlers.Response'
            - properties:
                data:
                  $ref: '#/definitions/models.Comment'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: create comment by ID
      tags:
      - comments
  /posts:
    get:
      consumes:
      - application/json
      - text/xml
      produces:
      - application/json
      - application/xml
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handlers.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Post'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: get all posts
      tags:
      - posts
  /posts/{id}:
    delete:
      consumes:
      - application/json
      - text/xml
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      - application/xml
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handlers.Response'
            - properties:
                data:
                  $ref: '#/definitions/models.Post'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: delete post by ID
      tags:
      - posts
    get:
      consumes:
      - application/json
      - text/xml
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      - application/xml
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handlers.Response'
            - properties:
                data:
                  $ref: '#/definitions/models.Post'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: get post by ID
      tags:
      - posts
    patch:
      consumes:
      - application/json
      - text/xml
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      - application/xml
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handlers.Response'
            - properties:
                data:
                  $ref: '#/definitions/models.Post'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: particular update post by ID
      tags:
      - posts
    post:
      consumes:
      - application/json
      - text/xml
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      - application/xml
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handlers.Response'
            - properties:
                data:
                  $ref: '#/definitions/models.Post'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: create post by ID
      tags:
      - posts
  /users/confirmation:
    post:
      consumes:
      - application/json
      - text/xml
      parameters:
      - description: raw request body
        in: body
        name: code
        required: true
        schema:
          $ref: '#/definitions/handlers.CodeRequestBoby'
      produces:
      - application/json
      - application/xml
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: confirm registration/reset password with 6-digit code from email/sms
      tags:
      - users
  /users/registration:
    post:
      consumes:
      - application/json
      - text/xml
      description: |-
        Password should contain:
        - minimum of one small case letter
        - minimum of one upper case letter
        - minimum of one digit
        - minimum of one special character
        - minimum 8 characters length
      parameters:
      - description: raw request body
        in: body
        name: registration
        required: true
        schema:
          $ref: '#/definitions/handlers.RegistrationRequestBody'
      produces:
      - application/json
      - application/xml
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: registration user by credentionals
      tags:
      - users
swagger: "2.0"
